name: CI
on: [push, pull_request]
jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ignore: git-repo-age
      - run: npx awesome-lint
